language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - PROFILE=ci
    - PROFILE=spring43-next
    - PROFILE=spring5,hibernate-43
    - PROFILE=spring5-next,hibernate-43
    - PROFILE=spring51-next,hibernate-52
    - PROFILE=hibernate-41
    - PROFILE=hibernate-42
    - PROFILE=hibernate-42-next
    - PROFILE=hibernate-43
    - PROFILE=hibernate-43-next
    - PROFILE=hibernate-5
    - PROFILE=hibernate-51
    - PROFILE=hibernate-51-next
    - PROFILE=hibernate-52
    - PROFILE=hibernate-52-next
    - PROFILE=hibernate-53
    - PROFILE=hibernate-53-next
    - PROFILE=hibernate-54-next
    - PROFILE=eclipselink-next
    - PROFILE=eclipselink-27-next
    - PROFILE=querydsl-next

addons:
  apt:
    packages:
    - oracle-java8-installer

sudo: false

cache:
  directories:
    - $HOME/.m2

before_install:
  - test ! -f ~/.m2/settings.xml || rm ~/.m2/settings.xml

install: true

script: "mvn clean dependency:list test -P${PROFILE} -Dsort -Dbundlor.enabled=false -B"
notifications:
  slack:
    secure: VYoJ2D6BM3etTNHJArJ47rVvj49PRZ+eIg12itOzlQSCnsPPob9X2OJVZ8Umatfx6TyP+rOrJAz+pqA1geumEzx+dIWTtBf6og703XKS9feLpM7sa1DupdstlGu506Wwevmb7nUq/Ct0ziCZykD3Cqu9tOhnai5wWlULBYDQ4WE=
